version: "3"
services:
  server:
    image: frarm2014/spring-boot3-rest:v1
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-springboot3:3306/db_example?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysql-springboot3

  mysql-springboot3:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_example
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword

networks:
  springmysql-net: